"""
Operator Zoo: Catalog all operators that arise naturally from the seed.

For each operator we compute:
  - Matrix representation
  - Eigenvalues and eigenvectors
  - Determinant (invertible?)
  - Whether it commutes with each other operator
  - The group generated by composition

This is a TOOL: the operator zoo is a "mixer board" where each operator
is a knob. Composing operators creates new dynamics. The question is:
what's the full group, and what combinations produce interesting behavior?

OPERATORS FROM THE SEED:
  O1 → Z₃ rotation (cyclic permutation of {T, C, B})
  O1 → Z₃ reflection (swap T↔C, fix B)
  O2 → Binary toggle (swap within pairs)
  O3 → Boundary projection (absorb to boundary)
  O4 → U(1) phase rotation (continuous, embedded)
  O5 → Shift operator (memory/counting)
  O8 → Fixed-point projector

NEW QUESTION: What group do these generate? Is it bigger than expected?
"""

import numpy as np
from typing import Dict, List, Tuple, Optional
from itertools import product as cart_product


# ============================================================================
# All operators on the 3-state Z₃ system
# ============================================================================

def op_identity() -> np.ndarray:
    """Identity: do nothing."""
    return np.eye(3)


def op_z3_rotation() -> np.ndarray:
    """Z₃ rotation: T→C→B→T (cyclic permutation).
    Forced by O1: the distinction cycles through all three states.
    """
    return np.array([
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
    ], dtype=float)


def op_z3_rotation_inv() -> np.ndarray:
    """Z₃ rotation inverse: T→B→C→T.
    The other direction of cycling.
    """
    return np.array([
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
    ], dtype=float)


def op_tc_swap() -> np.ndarray:
    """T↔C swap (reflection): swap thing and complement, fix boundary.
    Forced by O1 symmetry: thing and complement are symmetric.
    """
    return np.array([
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
    ], dtype=float)


def op_tb_swap() -> np.ndarray:
    """T↔B swap: swap thing and boundary.
    NOT forced by O1 alone (boundary is special per O3).
    Included for completeness.
    """
    return np.array([
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
    ], dtype=float)


def op_cb_swap() -> np.ndarray:
    """C↔B swap: swap complement and boundary.
    NOT forced by O1 alone.
    """
    return np.array([
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
    ], dtype=float)


def op_boundary_absorb() -> np.ndarray:
    """Boundary absorption: everything → boundary.
    Forced by O3 (boundary has weight — taken to extreme).
    NOT invertible (det = 0). Projects onto boundary.
    """
    return np.array([
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
    ], dtype=float)


def op_boundary_project() -> np.ndarray:
    """Project onto boundary subspace: kill T and C, keep B.
    Projection operator (idempotent: P² = P).
    """
    return np.array([
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
    ], dtype=float)


def op_live_project() -> np.ndarray:
    """Project onto live subspace: keep T and C, kill B.
    Complement of boundary projection.
    """
    return np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
    ], dtype=float)


def op_uniform_mix() -> np.ndarray:
    """Uniform mixing: all states → equal mixture.
    Maximum entropy operator. Not invertible.
    """
    return np.full((3, 3), 1/3)


def op_z3_dft() -> np.ndarray:
    """Discrete Fourier Transform on Z₃.
    The change-of-basis to the frequency domain.
    Eigenvalues of Z₃ rotation become diagonal.
    """
    omega = np.exp(2j * np.pi / 3)
    F = np.array([
        [1, 1, 1],
        [1, omega, omega**2],
        [1, omega**2, omega**4],
    ]) / np.sqrt(3)
    return F


def op_stochastic_absorbing(p_ex: float, p_ab: float) -> np.ndarray:
    """Parameterized absorbing transition.
    From the spectral gap audit — the tunable operator.
    """
    p_stay = 1 - p_ex - p_ab
    return np.array([
        [p_stay, p_ex, 0],
        [p_ex, p_stay, 0],
        [p_ab, p_ab, 1],
    ])


# ============================================================================
# Analysis tools
# ============================================================================

def analyze_operator(M: np.ndarray, name: str) -> Dict:
    """Full analysis of a single operator."""
    eigs = np.linalg.eigvals(M)
    det = np.linalg.det(M)
    trace = np.trace(M)

    # Check if it's a projection (M² = M)
    is_projection = np.allclose(M @ M, M, atol=1e-10)

    # Check if it's involutory (M² = I)
    is_involution = np.allclose(M @ M, np.eye(len(M)), atol=1e-10)

    # Check if it's unitary (M†M = I for complex, M^T M = I for real)
    is_orthogonal = np.allclose(M.T @ M, np.eye(len(M)), atol=1e-10)

    # Check if column-stochastic (columns sum to 1, entries ≥ 0)
    is_stochastic = (np.all(M >= -1e-10) and
                     np.allclose(M.sum(axis=0), 1, atol=1e-10))

    # Order: smallest k such that M^k = I (or 0 if none, up to 12)
    order = 0
    power = np.eye(len(M))
    for k in range(1, 13):
        power = power @ M
        if np.allclose(power, np.eye(len(M)), atol=1e-10):
            order = k
            break

    return {
        'name': name,
        'matrix': M,
        'eigenvalues': eigs,
        'det': det,
        'trace': trace,
        'is_invertible': abs(det) > 1e-10,
        'is_projection': is_projection,
        'is_involution': is_involution,
        'is_orthogonal': is_orthogonal,
        'is_stochastic': is_stochastic,
        'order': order,  # 0 = infinite or >12
    }


def commutator_table(operators: Dict[str, np.ndarray]) -> np.ndarray:
    """Compute the commutation table: [A, B] = AB - BA.

    Returns matrix of commutator norms. Zero means they commute.
    """
    names = list(operators.keys())
    n = len(names)
    table = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            A = operators[names[i]]
            B = operators[names[j]]
            if A.shape == B.shape and np.isrealobj(A) and np.isrealobj(B):
                comm = A @ B - B @ A
                table[i, j] = np.linalg.norm(comm)
            else:
                table[i, j] = -1  # incompatible

    return table, names


def find_generated_group(generators: List[np.ndarray], max_size: int = 100) -> List[np.ndarray]:
    """Find the group generated by a list of matrices (closure under multiplication).

    Uses BFS: start with generators, multiply all pairs, add new elements,
    repeat until no new elements found.
    """
    def matrix_in_list(M, lst, tol=1e-10):
        for X in lst:
            if M.shape == X.shape and np.allclose(M, X, atol=tol):
                return True
        return False

    group = [np.eye(generators[0].shape[0])]  # Start with identity
    for g in generators:
        if not matrix_in_list(g, group):
            group.append(g.copy())

    changed = True
    while changed and len(group) < max_size:
        changed = False
        new_elements = []
        for A in group:
            for B in group:
                AB = A @ B
                if not matrix_in_list(AB, group) and not matrix_in_list(AB, new_elements):
                    new_elements.append(AB)
                    changed = True
        group.extend(new_elements)

    return group


# ============================================================================
# The Zoo
# ============================================================================

def build_zoo() -> Dict[str, Dict]:
    """Build and analyze the complete operator zoo."""

    # All real 3×3 operators from the seed
    operators = {
        'I':         op_identity(),
        'R':         op_z3_rotation(),
        'R²':        op_z3_rotation_inv(),
        'σ_TC':      op_tc_swap(),
        'σ_TB':      op_tb_swap(),
        'σ_CB':      op_cb_swap(),
        'Π_B':       op_boundary_project(),
        'Π_L':       op_live_project(),
        'Abs':       op_boundary_absorb(),
        'Mix':       op_uniform_mix(),
    }

    analyses = {}
    for name, M in operators.items():
        analyses[name] = analyze_operator(M, name)

    return operators, analyses


def main():
    """Run the operator zoo catalog."""

    print("█" * 70)
    print("  OPERATOR ZOO: All natural operators from the seed")
    print("█" * 70)

    operators, analyses = build_zoo()

    # Print individual analyses
    for name, a in analyses.items():
        print(f"\n{'─'*60}")
        print(f"  {name}: {a['name']}")
        print(f"{'─'*60}")
        print(f"  Matrix:")
        for row in a['matrix']:
            print(f"    [{', '.join(f'{x:7.4f}' for x in row)}]")
        eig_str = ', '.join(f'{e:.4f}' if np.isreal(e) else f'{e:.4f}' for e in a['eigenvalues'])
        print(f"  Eigenvalues: {eig_str}")
        print(f"  det = {a['det']:.4f}  trace = {a['trace']:.4f}")
        props = []
        if a['is_invertible']:    props.append('invertible')
        if a['is_projection']:    props.append('projection')
        if a['is_involution']:    props.append('involution')
        if a['is_orthogonal']:    props.append('orthogonal')
        if a['is_stochastic']:    props.append('stochastic')
        if a['order'] > 0:        props.append(f'order={a["order"]}')
        print(f"  Properties: {", ".join(props) if props else "none"}")

    # Commutator table
    print(f"\n{'='*70}")
    print("  COMMUTATOR TABLE: ‖[A, B]‖  (0 = commutes)")
    print(f"{'='*70}")

    # Only real operators for commutator table
    real_ops = {k: v for k, v in operators.items()}
    table, names = commutator_table(real_ops)

    # Print header
    header = "        " + "".join(f"{n:>8}" for n in names)
    print(header)
    print("  " + "─" * (len(header) - 2))
    for i, name in enumerate(names):
        row_str = f"  {name:>6}" + "".join(
            f"{'  ·':>8}" if table[i, j] < 1e-10 else f"{table[i, j]:>8.3f}"
            for j in range(len(names))
        )
        print(row_str)

    # Find commuting pairs
    print(f"\n  Commuting pairs (non-trivial):")
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            if table[i, j] < 1e-10 and names[i] != 'I':
                print(f"    [{names[i]}, {names[j]}] = 0")

    # Group generation
    print(f"\n{'='*70}")
    print("  GROUP GENERATION: What groups do subsets generate?")
    print(f"{'='*70}")

    # S₃ from rotations + one swap
    print("\n  Generators: {R, σ_TC}  (Z₃ rotation + thing↔complement swap)")
    s3_group = find_generated_group([op_z3_rotation(), op_tc_swap()])
    print(f"  Generated group order: {len(s3_group)}")
    if len(s3_group) == 6:
        print(f"  → This is S₃ (symmetric group on 3 elements)")
        print(f"  → S₃ is the FULL permutation group of {{T, C, B}}")
    else:
        print(f"  → Order {len(s3_group)} group")

    # Z₃ from rotation alone
    print("\n  Generator: {R}  (Z₃ rotation only)")
    z3_group = find_generated_group([op_z3_rotation()])
    print(f"  Generated group order: {len(z3_group)}")
    print(f"  → Z₃ (cyclic group)")

    # Z₂ from swap alone
    print("\n  Generator: {σ_TC}  (thing↔complement swap only)")
    z2_group = find_generated_group([op_tc_swap()])
    print(f"  Generated group order: {len(z2_group)}")
    print(f"  → Z₂ (the 'color' group)")

    # All permutations
    print("\n  Generators: {R, σ_TC, σ_TB}  (all three swaps)")
    full_group = find_generated_group([op_z3_rotation(), op_tc_swap(), op_tb_swap()])
    print(f"  Generated group order: {len(full_group)}")
    print(f"  → Still S₃ (adding σ_TB doesn't grow beyond permutations)")

    # What's the FORCED subgroup?
    print(f"\n{'='*70}")
    print("  WHAT'S FORCED vs CHOSEN?")
    print(f"{'='*70}")
    print()
    print("  FORCED by O1 alone:")
    print("    R (Z₃ rotation): thing→complement→boundary→thing")
    print("    σ_TC (T↔C swap): thing and complement are symmetric")
    print("    Together: {R, σ_TC} generate S₃ (order 6)")
    print()
    print("  NOT forced by O1:")
    print("    σ_TB (T↔B swap): boundary is SPECIAL (O3), not interchangeable with T")
    print("    σ_CB (C↔B swap): same reason")
    print("    → O3 BREAKS the full S₃ to a subgroup")
    print()
    print("  With O3 (boundary is special):")
    print("    Only σ_TC is forced (T↔C are peers, B is distinguished)")
    print("    R is still forced (cycling through all three)")
    print("    But σ_TB and σ_CB violate O3 (they treat B as interchangeable)")
    print()
    print("  HONEST SUBGROUP from O1+O3:")
    print("    {I, R, R², σ_TC, σ_TC·R, σ_TC·R²} = S₃")
    print("    WAIT — R also moves B, so R treats B as interchangeable!")
    print()

    # This is interesting: does Z₃ rotation violate O3?
    print("  PROBLEM: Z₃ rotation sends B→T, which means boundary")
    print("  BECOMES a thing. Does O3 allow this?")
    print()
    print("  O3 says: 'The boundary between things is itself a thing.'")
    print("  This means B IS a thing, so it CAN participate in rotations.")
    print("  But it also has 'ontological weight' — it's special.")
    print()
    print("  RESOLUTION: O3 makes B a DISTINGUISHED element, not an IMMOVABLE one.")
    print("  R is allowed. σ_TB is NOT forced (nothing requires T↔B symmetry).")
    print("  The forced group is S₃ = <R, σ_TC>, but the forced DYNAMICS should")
    print("  treat B differently (absorbing, heavier, etc.)")
    print()

    # Tunable parameters
    print(f"{'='*70}")
    print("  THE MIXER BOARD: Tunable operator combinations")
    print(f"{'='*70}")
    print()
    print("  Each operator is a 'knob'. Composition creates new dynamics:")
    print()
    print("    Knob 1: R (rotation) — controls cycling speed")
    print("    Knob 2: σ_TC (swap) — controls T↔C exchange rate")
    print("    Knob 3: Π_B (boundary project) — controls absorption rate")
    print("    Knob 4: Π_L (live project) — controls live-sector isolation")
    print()
    print("  Mixing formula: M(a,b,c) = a·R + b·σ_TC + c·Π_B + (1-a-b-c)·I")
    print("  This creates a parameterized operator family.")
    print()

    # Demo the mixer
    print("  MIXER DEMO: varying weights")
    print(f"  {'a':>5} {'b':>5} {'c':>5} | {'det':>8} {'gap':>8} | {'type':>15}")
    print("  " + "-" * 55)

    test_mixes = [
        (1, 0, 0, "pure rotation"),
        (0, 1, 0, "pure swap"),
        (0, 0, 1, "pure absorb"),
        (0.5, 0.5, 0, "rot+swap"),
        (0.33, 0.33, 0.33, "equal mix"),
        (0, 0, 0, "identity"),
        (0.2, 0.2, 0.6, "mostly absorb"),
        (0.5, 0, 0.5, "rot+absorb"),
    ]

    for a, b, c, label in test_mixes:
        d = 1 - a - b - c
        M = a * op_z3_rotation() + b * op_tc_swap() + c * op_boundary_project() + d * op_identity()
        det = np.linalg.det(M)
        eigs = np.sort(np.abs(np.linalg.eigvals(M)))[::-1]
        gap = eigs[0] - eigs[1] if len(eigs) > 1 else 0
        print(f"  {a:>5.2f} {b:>5.2f} {c:>5.2f} | {det:>8.4f} {gap:>8.4f} | {label}")

    print()
    print("█" * 70)
    print("  ZOO COMPLETE")
    print("█" * 70)
    print()
    print("  KEY FINDINGS:")
    print("    1. {R, σ_TC} generates S₃ (order 6) — the full permutation group")
    print("    2. Z₃ rotation alone generates Z₃ (order 3)")
    print("    3. σ_TC alone generates Z₂ (order 2)")
    print("    4. S₃ is the natural symmetry group of the 3-state system")
    print("    5. O3 distinguishes B but doesn't prevent rotation through it")
    print("    6. The mixer board has 3 independent knobs (rot, swap, absorb)")
    print("    7. Different mixes produce gaps from 0 to 1")
    print("    8. Only rotation is orthogonal; absorb/project are singular")


if __name__ == "__main__":
    main()
